setup: dev_setup env_setup

dev_setup:
	pip install -r requirements.txt

env_setup:
	$(PYTHON) -m venv venv

env_activate:
	source venv/bin/activate

env_deactivate:
	deactivate

wheel:
	$(PYTHON) -m build -w

sdist:
	$(PYTHON) -m build -s

publish: sdist wheel
	$(PYTHON) -m twine upload dist/*

install:
	pip install -e .


clear:
	rm -rf build dist rule34Py.egg-info

.PHONY: wheel sdist publish clear env-activate env-setup env-deactivate dev_setup setup install