name: Build the project
description: Installs project dependencies and builds the project

inputs:
  latest_python:
    default: false

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ">=3.5"
        check-latest: ${{ inputs.latest_python }}

    - name: Build documentation
      shell: bash
      run: |
        python3 -m pip install .[docs]
        make html
