name: Build and test
description: Builds and tests the project

inputs:
  python_version:
    default: ""  # empty will make setup-python default to the env python
  latest_python:
    default: false

runs:
  using: "composite"
  steps:
    - name: Install host tooling
      shell: bash
      run: |
        python -m pip install --upgrade setuptools build
        python -m pip install . .[dev] .[docs] .[test]
        pip freeze \
          --exclude rule34Py \
          >build/requirements.txt

    - name: Build wheel and dist
      shell: bash
      run: |
        make all
        make dist

    - name: Run unit tests
      shell: bash
      run: make check

    - name: Build documentation
      shell: bash
      run: make html
  