name: Build and test
description: Builds and tests the project

inputs:
  python-version:
    default: '3.x'

runs:
  using: "composite"
  steps:

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install host python dependencies
      shell: bash
      run: |
        pipx install poetry
        poetry self update
        poetry install

    - name: Build wheel and dist
      shell: bash
      run: |
        make all
        make dist

    - name: Build documentation
      shell: bash
      run: make html

    - name: Upload build artifacts
      if: ${{ inputs.python-version == '3.x' }}
      uses: actions/upload-artifact@v4
      with:
        name: build.${{ github.run_id }}-${{ github.run_number }}.${{ runner.os }}-py${{ inputs.python-version }}
        path: ./build
        retention-days: 14
